name: Build
on:
  push:
    branches:
      - rewrite/react

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-latest: [20.04, 18.04]
        node-version: [11.x, 12.x]
      

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
      
    - run: npm install

    