name: Deploy
on: 
  push:
    branches:
      - rewrite/react

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-latest: [20.04
        node-version: [11.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Docker build
      uses: docker/build-push-action@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm start

    - run: docker pull docker.pkg.github.com/andrewnijmeh/andrewnijmeh.net/api:1.5.0  

    - run: docker run api:1.50
